### ISSUE TITLE
Filed to get the adhoc command output

### ISSUE THREAD

**Issue by anannaya** [lusis/go-rundeck#35]

**Comment by anannaya** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x134a807]

goroutine 1 [running]:
github.com/lusis/go-rundeck/pkg/rundeck.(*Client).checkRequiredAPIVersion(0x0, 0x1504760, 0x1814178, 0x6, 0xc000428000)
	/Users/ananayak/data/STUDIES/PROGRAMMING/Go_programs/go/src/github.com/lusis/go-rundeck/pkg/rundeck/version.go:11 +0x37
github.com/lusis/go-rundeck/pkg/rundeck.(*Client).GetExecutionOutput(0x0, 0xaa50, 0xc0001a9d78, 0x1, 0x1)
	/Users/ananayak/data/STUDIES/PROGRAMMING/Go_programs/go/src/github.com/lusis/go-rundeck/pkg/rundeck/execution.go:71 +0x47
main.main()
	/Users/ananayak/data/STUDIES/PROGRAMMING/Go_programs/go/src/cisco/rundeck/main.go:83 +0x99b
exit status 2
